spring:
  application:
    name: MANCHESTER

server:
  port: 8081
  error:
    include-stacktrace: on-param

# eureka:
#    client:
#       serviceUrl:
#          defaultZone: http://localhost:8761/eureka